---
title: "History of db-benchmark timings"
output:
  html_document:
    self_contained: no
    toc: false
    includes:
      in_header: ga.html
---

```{r opts, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE, cache=FALSE)
```

```{r render}
report_name = "history"
# Rscript -e 'rmarkdown::render("history.Rmd", output_dir="public")' # has to be output_dir='public' as there is hardcode in benchplot for that path
```

```{r init}
library(lattice)
source("report.R")
ld = time_logs()
```

## Timings over time

### groupby

0% NAs, unsorted

```{r hist_groupby_plot, fig.width=8, fig.height=48}
stopifnot(length(unique(ld$nodename))==1L)
p = sapply(setNames(nm=as.character(unique(ld$solution))), simplify = FALSE, function(s)
  lattice::xyplot(time_sec_1 ~ ibatch | k+in_rows, ld[nasorted=="0% NAs, unsorted"],
                type="l", grid=TRUE, groups=question,
                subset=solution==s, main=s,
                xlab = "benchmark run",
                ylab = "seconds",
                scales=list(y=list(
                  relation="free",
                  limits=rep(ld[solution==s, .(ylim=max(c(0, time_sec_1), na.rm=TRUE)), in_rows][ylim>0, list(list(c(0, ylim))), in_rows]$V1, each=3)
                )),
                auto.key=list(points=FALSE, lines=TRUE))
)
sapply(seq_along(p), function(i) print(p[[i]], split=c(1, i, 1, length(p)), more=i!=length(p))) -> nul
```


```{r status, child="rmarkdown_child/status.Rmd"}
```
